version: "3.9"

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "lamoda", "-U", "postgres" ]
      interval: 5s
      retries: 5
      start_period: 5s

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    env_file: .env
    command: [ "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}?sslmode=disable", "-path", "/migrations", "up" ]
    depends_on:
      postgres:
        condition: service_healthy

  lamoda:
    build: .
    container_name: lamoda
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      - postgres
      - migrate
