definitions:
  model.Product:
    properties:
      id:
        type: integer
      name:
        type: string
      quantity:
        type: integer
      size:
        type: integer
    type: object
  model.ReserveRequest:
    properties:
      product_ids:
        items:
          type: integer
        type: array
    type: object
  model.Storage:
    properties:
      available:
        type: boolean
      id:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /product/:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: List of products
          schema:
            items:
              $ref: '#/definitions/model.Product'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: product
      summary: List Products
      tags:
      - Product
    post:
      consumes:
      - application/json
      parameters:
      - description: Product
        in: body
        name: Product
        required: true
        schema:
          $ref: '#/definitions/model.Product'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            type: product
        "500":
          description: Internal Server Error
          schema:
            type: product
      summary: Create
      tags:
      - Product
  /product/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Product ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Product details
          schema:
            type: product
        "400":
          description: Bad Request
          schema:
            type: product
        "500":
          description: Internal Server Error
          schema:
            type: product
      summary: Get Product by ID
      tags:
      - Product
  /product/available/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Storage ID
        in: path
        name: storageID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            type: product
        "500":
          description: Internal Server Error
          schema:
            type: product
      summary: Get Available Quantity
      tags:
      - Product
  /product/release:
    post:
      consumes:
      - application/json
      parameters:
      - description: Release request
        in: body
        name: ReleaseRequest
        required: true
        schema:
          $ref: '#/definitions/model.ReserveRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            type: product
        "500":
          description: Internal Server Error
          schema:
            type: product
      summary: Release Reserved Products
      tags:
      - Product
  /product/reserve:
    post:
      consumes:
      - application/json
      parameters:
      - description: Reserve request
        in: body
        name: ReserveRequest
        required: true
        schema:
          $ref: '#/definitions/model.ReserveRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            type: product
        "500":
          description: Internal Server Error
          schema:
            type: product
      summary: Reserve Product
      tags:
      - Product
  /storage/:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: List of storages
          schema:
            items:
              $ref: '#/definitions/model.Storage'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: warehouse
      summary: List Storages
      tags:
      - Storage
    post:
      consumes:
      - application/json
      parameters:
      - description: Storage
        in: body
        name: warehouse
        required: true
        schema:
          $ref: '#/definitions/model.Storage'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            type: warehouse
        "500":
          description: Internal Server Error
          schema:
            type: warehouse
      summary: Create Storage
      tags:
      - Storage
  /storage/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Storage ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Storage details
          schema:
            type: warehouse
        "400":
          description: Bad Request
          schema:
            type: warehouse
        "500":
          description: Internal Server Error
          schema:
            type: warehouse
      summary: Get Storage by ID
      tags:
      - Storage
swagger: "2.0"
